version: '3.7'

volumes:
  data:

services:
  mysql:
    container_name: mysql_dev
    image: mysql:5.7.32
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'default'
    networks:
      - mysql-phpmyadmin-network

  phpmyadmin:
    container_name: phpmyadmin_dev
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - '7777:80'
    environment:
      PMA_ARBITRARY: '1'
      PMA_HOST: 'mysql'
      PMA_PORT: '3306'
    networks:
      - mysql-phpmyadmin-network

networks: 
  mysql-phpmyadmin-network:
    driver: bridge